#!/usr/bin/env sh

# yabairc wiki
# https://github.com/koekeishiya/yabai/wiki/

#skhdrc wiki
# https://github.com/koekeishiya/skhd


#YABAI STUFF

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             first_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               on
#yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        0.98
yabai -m config normal_window_opacity        0.90
# yabai -m config window_border                on
# yabai -m config window_border_width          8
#yabai -m config active_window_border_color   0xff649BED
# yabai -m config active_window_border_color  0xff775759 
# yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  40
yabai -m config bottom_padding               12
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   20

#SPACEBAR_HEIGHT=$(spacebar -m config height)
#yabai -m config external_bar all:$SPACEBAR_HEIGHT:0

# My custom space names for my 3 monitor setup. These names are used in some of my scripts.
yabai -m space 1 --label main
yabai -m space 2 --label work
yabai -m space 3 --label social
yabai -m space 4 --label dev
yabai -m space 5 --label five
yabai -m space 6 --label six
yabai -m space 9 --label nine

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alacritty$" sticky=on display=2
yabai -m rule --add app="^Calculator$" sticky=on layer=above manage=off
yabai -m rule --add app="Fantastical" manage=off
yabai -m rule --add app="Calendar" manage=off display=3
yabai -m rule --add app="^Facetime$" manage=off display=3
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^Private Internet Access$" manage=off
yabai -m rule --add app="^Mullvad VPN$" manage=off
yabai -m rule --add app="Discord" space=social
yabai -m rule --add app="Safari" space=web

# general space settings
#yabai -m config focused_border_skip_floating  1
#yabai -m config --space 3 layout             float

echo "yabai configuration loaded.."

#END
